// examples/next-v2/pages/index.tsx
import type { NextPage } from 'next'
import { useEffect, useState } from 'react'
import { getPerson, Person, getIsServer } from '../telefunc/persons.telefunc'

const Home: NextPage = () => {
  const [person, setPersion] = useState<null | Person>()
  const [isServer, setIsServer] = useState<boolean>()

  const fetchPerson = () => {
    getPerson(0).then((person) => {
      setPersion(person)
    })
    getIsServer().then((isServer) => {
      setIsServer(isServer)
    })
  }

  useEffect(() => {
    fetchPerson()
  }, [])

  return (
    <div id="view">
      First name: {person?.firstName}
      <br />
      Last name: {person?.lastName}
      <br />
      server: {isServer ? 'true' : 'false'}
    </div>
  )
}

export default Home

// examples/nuxt/pages/index.vue
<template>
  <div id="view">
    First name: {{ person.firstName }}
    <br />
    Last name: {{ person.lastName }}
    <br />
    Telefunction ran on server: {{ telefunctionWasRunInServer ? 'true' : 'false' }}
  </div>
</template>

<script>
export default {
  mounted: function () {
    this.$store.dispatch('loadData')
  },
  computed: {
    person: function () {
      return this.$store.state.person
    },
    telefunctionWasRunInServer: function () {
      return this.$store.state.telefunctionWasRunInServer
    },
  },
}
</script>
