// examples/next/pages/person.jsx
export default Page

import { useEffect, useState } from 'react'
import { getPerson } from '../person.telefunc'

function Page() {
  const [person, setPersion] = useState()

  useEffect(() => {
    getPerson(1).then((person) => {
      setPersion(person)
    })
  }, [])

  return (
    <>
      First name: {person?.firstName}
      <br />
      Last name: {person?.lastName}
      <br />
    </>
  )
}

// examples/nuxt/pages/person.vue
<template>
  <div>
    First name: {{ person.firstName }}
    <br />
    Last name: {{ person.lastName }}
    <br />
    <NuxtLink to="/">Home</NuxtLink>
  </div>
</template>

<script>
import { getPerson } from '../person.telefunc'

export default {
  async asyncData() {
    const person = await getPerson(0)
    return { person }
  },
}
</script>
