// examples/svelte-kit/src/lib/TodoList.svelte
<script>
  import { onNewTodo } from './TodoList.telefunc.js'
  export let todoItemsInitial;

  let todoItems = todoItemsInitial
  let text = ''

  async function handleSubmit() {
    let {todoItems: newTodoItems} = await onNewTodo({text})
    text = ''
    todoItems = newTodoItems
  }
</script>

<ul>
  {#each todoItems as todoItem, i}
    <li key={i}>{todoItem.text}</li>
  {/each}
  <li>
    <form on:submit|preventDefault={handleSubmit}>
      <input type="text" bind:value={text} />
      <button type="submit">Add to-do</button>
    </form>
  </li>
</ul>

// examples/vite-plugin-ssr/pages/index/TodoList.jsx
import React, { useState } from 'react'
import { onNewTodo } from './TodoList.telefunc.js'

export { TodoList }

function TodoList({ todoItemsInitial }) {
  const [todoItems, setTodoItems] = useState(todoItemsInitial)
  const [text, setText] = useState('')
  return (
    <>
      <ul>
        {todoItems.map((todoItem, i) => (
          <li key={i}>{todoItem.text}</li>
        ))}
        <li>
          <form
            onSubmit={async (ev) => {
              ev.preventDefault()
              const { todoItems } = await onNewTodo({ text })
              setText('')
              setTodoItems(todoItems)
            }}
          >
            <input type="text" onChange={(ev) => setText(ev.target.value)} value={text} />{' '}
            <button type="submit">Add to-do</button>
          </form>
        </li>
      </ul>
    </>
  )
}
