// examples/nuxt/components/TodoList.vue
<template>
  <div>
    <h1>{{ userName }}'s to-do list</h1>
    <ul>
      <li v-for="item in todoItems">{{ item.text }}</li>
      <li>
        <form v-on:submit.prevent="onSubmit">
          <input type="text" v-model="text" />
          <button type="submit">Add to-do</button>
        </form>
      </li>
    </ul>
  </div>
</template>

<script>
import { getTodoListData, onNewTodo } from './TodoList.telefunc.js'
export default {
  data: () => ({
    todoItems: [],
    text: '',
    userName: '',
  }),
  methods: {
    async onSubmit(ev) {
      const { text } = this
      this.text = ''
      const { todoItems } = await onNewTodo({ text })
      this.todoItems = todoItems
    },
  },
  async fetch() {
    const { todoItems, userName } = await getTodoListData()
    this.todoItems.push(...todoItems)
    this.userName = userName
  },
}
</script>

// examples/next/components/TodoList.jsx
import React, { useState } from 'react'
import { onNewTodo } from './TodoList.telefunc.js'

export { TodoList }

function TodoList({ todoItemsInitial }) {
  const [todoItems, setTodoItems] = useState(todoItemsInitial)
  const [text, setText] = useState('')
  return (
    <>
      <ul>
        {todoItems.map((todoItem, i) => (
          <li key={i}>{todoItem.text}</li>
        ))}
        <li>
          <form
            onSubmit={async (ev) => {
              ev.preventDefault()
              setText('')
              const { todoItems } = await onNewTodo({ text })
              setTodoItems(todoItems)
            }}
          >
            <input type="text" onChange={(ev) => setText(ev.target.value)} value={text} />{' '}
            <button type="submit">Add to-do</button>
          </form>
        </li>
      </ul>
    </>
  )
}
